server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cloud-gateway1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:80   #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/payment/get/**   #断言,路径相匹配的进行路由

        - id: cloud-gateway2
          uri: http://localhost:80
          predicates:
            - Path=/consumer/payment/create/**  #断言,路径相匹配的进行路由

#        - id: cloud-gateway3
#            uri: http://localhost:8002
#            predicates:
#              - Path=/payment/get/**   #断言,路径相匹配的进行路由
#
#        - id: cloud-gateway4
#            uri: http://localhost:8002
#            predicates:
#              - Path=/payment/lb/**   #断言,路径相匹配的进行路由
